### ISSUE TITLE
Interested in using facade approach instead?

### ISSUE THREAD

**Issue by skewty** [toreamun/asyncio-paho#1]
I found this repo after getting frustrated with [gmqtt](https://github.com/wialon/gmqtt).

I really appreciate the type hints and wanting to be like paho client as much as possible but found the approach you took lead to some undesirable traits like 3 connect methods and the access of protected members.

Would you be interested in altering this repo to use a facade instead (I would be willing to contribute / write it with you)?

We no longer have to contend with:
    - self.connect(...)
    - self.connect_async(...)
    - self.asyncio_connect(...)
and can instead offer only:
    - def connect(...) -> None
    - async def wait_connected() -> None

The documentation can be simplified to not require parts like:
> The classic Paho connect() is blocking. Paho connect_async() is not blocking, but returns before the connect is complete. Use asyncio_connect() to wait for connect to complete without blocking. This function also throws exception on connect failure. Please note that asyncio_connect() cannot be used together with on_connect /on_connect_fail (use asyncio_add_on_connect_listener and asyncio_add_on_connect_fail_listener instead of on_connect and on_connect_fail).

We could add in missing type hints (paho is missing a fair amount).

To help explain further here is a bit of code:

```python
import logging

from paho.mqtt.client import MQTT_CLEAN_START_FIRST_ONLY, Client

__all__ = ["AsyncClient"]

class _SyncClient(Client):
    """Exposes some protected values for AsyncClient

    This will help us avoid lines like:
    - self._asyncio_listeners._on_connect_forwarder,  # pylint: disable=protected-access
    - self._asyncio_listeners._on_connect_fail_forwarder,  # pylint: disable=protected-access
    """

    pass


class AsyncClient:
    """Facade around Paho Sync Client

    We pass through only the properties and methods that make sense and fix
    / add in type hints where they didn't exist before.
    """

    def __init__(self) -> None:
        self._client = _SyncClient()

    # we can add in missing type hints at the same time
    def enable_logger(self, logger: logging.Logger = None) -> None:
        self._client.enable_logger(logger)

    def disable_logger(self) -> None:
        self._client.disable_logger()

    # more missing type hints
    def username_pw_set(self, username: str, password: str = None) -> None:
        self._client.username_pw_set(username, password)
```

**Comment by toreamun** [comment]
I know that the approach brings some issues like you explain. But going down the facade road probably brings other issues along the way. One goal was to keep the transition from Paho simple be not taking away anything. A facade implementation has to implement facade for a lot of functions to meet that goal. If a facade approach should be followed, then i think that should be by creating a new facade class and keep the exising.

Have your tried [asyncio-mqtt](https://github.com/sbtinstruments/asyncio-mqtt)? That package can also be a nice alternative if you need async mqtt.
